// Wallet
export const COPY_MENU = 'CopyMenu'
export const QR_CODE = 'QrCode'
export const INVOICE_FORM = 'InvoiceForm'
export const SEND_FORM = 'SendForm'
export const EDIT_FEE = 'EditFee'
export const SHARE_MODAL = 'ShareModal'
export const TRANSACTION_DETAILS = 'TransactionDetails'
export const WALLET_SETTINGS = 'WalletSettings'
export const WALLET_CREATE = 'WalletCreate'
export const ADD_NEW_CURRENCY = 'AddNewCurrency'
export const INCOMING_INVOICE = 'IncomingInvoice'
