// Wallet
export const COPY_MENU = 'CopyMenu'
export const QR_CODE = 'QrCode'
export const INVOICE_FORM = 'InvoiceForm'
export const INVOICE_PREVIEW = 'InvoicePreview'
export const SEND_FORM = 'SendForm'
export const SEND_PREVIEW = 'SendPreview'
export const EDIT_FEE = 'EditFee'
export const SHARE_MODAL = 'ShareModal'
export const TRANSACTION_DETAILS = 'TransactionDetails'
export const WALLET_SETTINGS = 'WalletSettings'
export const WALLET_CREATE = 'WalletCreate'
export const ADD_NEW_CURRENCY = 'AddNewCurrency'
