export const IFRAME_INITED = 'iframeInited'
export const THEME_SELECTED = 'themeSelected'
export const PROFILE_CREATED = 'profileCreated'
export const RECOVER_CANCELED = 'recoverCancelled'
export const PROFILE_RECOVERED = 'profileRecovered'
export const IFRAME_DESTROYED = 'iframeDestroyed'
